### ISSUE TITLE
Logon error

### ISSUE THREAD

**Issue by Marlark** [gruijter/com.gruijter.hyundai_kia#4]
Looks like there have changed something in the login seq.

[2021-04-24 03:39:18] [31merror[39m: @EuropeController.login: sign in with EuropeanBrandAuthStrategy failed with error TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

Im using latest test version off the app and using Kia UVO.

// Ted

**Comment by gruijter** [comment]
Did you already upgrade to a kia account? Try logging out of the official uvo app, and login with the new kia account.

**Comment by Marlark** [comment]
I use the new kia account have for a while. Turns out my account had been locked. But that is fixed now. I did get some odd page errors the first time i restarted the app.  But after the second restart it worked without errors again.

// Ted

**Comment by gruijter** [comment]
Ok thx 4 the update. Why did you get locked out?
